version: '3'
services:
    backend:
      container_name: backend
      restart: always
      build: ./backend
      ports:
        - '5000:5000'
    frontend:
      container_name: frontend
      restart: always
      build: ./frontend
      ports:
        - '3000:3000'
      depends_on:
        - backend